
sudo: false
language: android
android:
  components:
# first 'tools' updates SDK tools 'til last version ** in remote repository number 10 **
  - tools
# second 'tools' updates SDK tools 'til last version ** in remote repository number 11 ** (current last one)
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-23
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod +x ./wait_for_emulator.sh
  - ./wait_for_emulator.sh
script:
# build app and assemble APK, in debug mode
  - ./gradlew assembleDebug
# run all the local unit tests of app module
  - ./gradlew :testDebug
# run all the instrumented tests of app module - DISABLED until we get an stable setup for Espresso in Travis
# - ./gradlew connectedDebugAndroidTest --info
# install app, then assemble and install instrumented tests of app module
  - ./gradlew :installDebug
  - ./gradlew :installDebugAndroidTest
# run sample instrumented unit test
  - adb shell am instrument -w -e debug false -e class com.owncloud.android.datamodel.OCFileUnitTest com.owncloud.android.test/android.support.test.runner.AndroidJUnitRunner
env:
  matrix:
  - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a